### ISSUE TITLE
DataFrame Error : df.sort("xx").take(num) will make hbase stop.

### ISSUE THREAD

**Issue by pzzs** [Huawei-Spark/hbase#8]
Table 

```
grade            int
class            int
subject          string  
teacher _name    string
teacher _age     int

keyCols : grade,class,subject
```

Data

```
1,1,subject_1,teacher_1_1_1,25
1,1,subject_2,teacher_1_2_1,25
1,1,subject_3,teacher_1_3_1,25
1,1,subject_4,teacher_1_4_1,25
1,1,subject_5,teacher_1_5_1,25
1,2,subject_1,teacher_1_1_1,25
1,2,subject_2,teacher_1_2_1,25
1,2,subject_3,teacher_1_3_1,25
1,2,subject_4,teacher_1_4_1,25
1,2,subject_5,teacher_1_5_1,25
1,3,subject_1,teacher_1_1_1,25
1,3,subject_2,teacher_1_2_1,25
...
...
```

Code

```
val hbaseContext =  new HBaseSQLContext(sc)
val df: DataFrame = hbaseContext.sql("Select * from spark_teacher_3key_df")
df.sort("grade").take(3)
```

then it did not return a result after a long time. and i find all region Servers of hbase is dead.

**Comment by yzhou2001** [comment]
This is a real problem. Could you try a SQL equivalent ?

select \* from ... order by grade limit 3

**Comment by pzzs** [comment]
yes, "select \* from spark_teacher_3key_df order by grade limit 2" has the same problem. But "select \* from spark_teacher_3key_df sort by grade limit 2" is good.

**Comment by pzzs** [comment]
df.orderBy("grade").take(2) has the same problem too

**Comment by xinyunh** [comment]
Solved and merged into branch Stratio-ToSpark1_4.(https://github.com/Huawei-Spark/hbase/commit/a2da76c3c61708ddf74e46e9238a1766c760671a)

Thank you!
